import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={poppins.className}
      >
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
  );
}
